name: Upload
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/push-kaggle-kernel@master
        with:
          slug: test-script
          title: test-script
          code_file: ./examples/kernel.py
          language: python
          kernel_type: script
          is_private: false
          competition_sources: |
            titanic
